name: Run Tests and Lint on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements_test.txt
        pip install flake8

    - name: Run flake8
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run scraping test manually (src/test.py)
      run: PYTHONPATH=. python src/test.py

